function dy = hopfInvertedsystem(t,y,c,omega,A,xMaxstate,reescaletime,maxBeta)
%y(3)=y(3)-traslation;
%Here the normalization is on doned previously. 
y(2) = y(2) * maxBeta;
y(3) = y(3) * xMaxstate(3);
y(4) = y(4) * xMaxstate(4);

dy = [reescaletime;

% Poly degreee 3
% reescaletime * ((-1)*(+c(2)+2*c(3)*(t)+3*c(4)*(t)^2))/maxBeta;

% Poly degreee 6
reescaletime * (-1) * ( ...
    c(2) ...
    + 2*c(3)*t ...
    + 3*c(4)*t.^2 ...
    + 4*c(5)*t.^3 ...
    + 5*c(6)*t.^4 ...
    + 6*c(7)*t.^5 ...
    + 7*c(8)*t.^6 ...
    + 8*c(9)*t.^7 ...
    + 9*c(10)*t.^8 ...
    + 10*c(11)*t.^9 ...
    + 11*c(12)*t.^10 ...
    )/maxBeta;


reescaletime * ((-(y(2))*y(3) - omega*y(4) - A*y(3)*(y(3)^2+y(4)^2))/xMaxstate(3));
reescaletime * ((omega*y(3) + (-(y(2)))*y(4) - A*y(4)*(y(3)^2+y(4)^2))/xMaxstate(4));
];