function dy = saddlenodeTimeReescale(t,y,c,xMaxstate,reescaletime,maxBeta)
% Copyright 2013, All Rights Reserved
% Code by Juan Diaz
% For Paper, "IHCV, identificaiton of hidden control variables"
% by Juan Diaz , Jesper Tegner et al.

dy = [reescaletime;
% reescaletime*(c(2)+2*c(3).*(t+c(5))+3.*c(4).*(t+c(5)).^2)/maxBeta;  
% -c(1)- 2*c(2)* (-y(1)+c(4)) - 3*c(3)*(-y(1)+c(4))^2;
reescaletime *( ...
    c(2) ...
    + 2*c(3)*(t+c(5)) ...
    + 3*c(4)*(t+c(5)).^2 ...
    + 4*c(6)*(t+c(5)).^3 ...
    + 5*c(7)*(t+c(5)).^4 ...
    + 6*c(8)*(t+c(5)).^5 ...
    + 7*c(9)*(t+c(5)).^6 ...
    + 8*c(10)*(t+c(5)).^7 ...
    + 9*c(11)*(t+c(5)).^8 ...
    + 10*c(12)*(t+c(5)).^9 ...
    + 11*c(13)*(t+c(5)).^10 ...
    )/maxBeta;

 % reescaletime*(c(1)+2*c(2).*(t)+3.*c(3).*t.^2)/maxBeta;
 % reescaletime*(c(2)+2*c(3).*(t)+3.*c(4).*t.^2)/maxBeta;
+reescaletime*(((y(2)*maxBeta)-(y(3)*xMaxstate(3)).^2))/xMaxstate(3)
];
